config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'users#index'

  # authenticated :user do
  #   root to: 'users#index', as: :authenticated_root
  # end

  # unauthenticated do
  #   root to: 'devise/sessions#new', as: :unauthenticated_root
  # end

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:create]
      resources :likes, only: [:create, :destroy]

      member do
        post 'likes', to: 'likes#create'
      end
    end

    get 'posts/page/:page', to: 'posts#index', on: :member, as: 'posts_page'
  end

  delete '/likes/:id', to: 'likes#destroy', as: 'like'

  post '/comments', to: 'comments#create', as: 'create_comment'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :text, presence: true

  after_save :update_post_comments_counter

  private

  def update_post_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :update_post_likes_counter

  private

  def update_post_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  belongs_to :author, class_name: 'User'
  belongs_to :user, foreign_key: 'author_id'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  after_save :update_user_posts_counter

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  def update_user_posts_counter
    author.increment!(:post_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  after_create :send_confirmation_instructions
  validates :name, presence: true
  validates :post_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  def recent_posts
    posts.includes(:comments).order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_referer

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name photo bio])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name photo bio])
  end

  private

  def set_referer
    session[:return_to] = request.referer if request.url != request.referer
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @user = @post.author
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      flash[:success] = 'Comment created successfully.'
      redirect_to user_post_path(@user, @post)
    else
      flash[:error] = 'Comment could not be created.'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like = @post.likes.build(like_params)

    if @like.save
      flash[:success] = 'Liked post!'
    else
      flash[:error] = 'Failed to like post.'
    end

    redirect_to user_post_path(@post.author, @post)
  end

  def destroy
    @like = Like.find(params[:id])
    @post = @like.post

    if @like.destroy
      flash[:success] = 'Unliked post.'
    else
      flash[:error] = 'Failed to unlike post.'
    end

    redirect_to user_post_path(@post.author, @post)
  end

  private

  def like_params
    params.require(:like).permit(:user_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]

  def new
    @post = Post.new
  end

  def index
    @user = User.includes(posts: :comments).find(params[:user_id])
    @posts = @user.posts.includes(:comments).paginate(page: params[:page], per_page: 10)
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
  end

  def create
    @user = current_user
    @post = @user.posts.build(post_params)
    if @post.save
      redirect_to user_posts_path(@user), notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  private

  def find_user
    @user = User.find(params[:user_id])
  end

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/posts_controllers.rb
# app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: %i[new create]
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.all
  end

  def set_user
    @user = User.includes(posts: :comments).find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/posts/index.html.erb
<head>
  <%= stylesheet_link_tag 'application', 'posts_index' %>
</head>

<div class="user-info">
  <img class="user-photo" src="<%= asset_path(@user.photo) %>" alt="<%= @user.name %>'s Photo" width="100" height="100" />
  <%= tag.div @user.name, class: 'user-name' %>
  <p class="no-posts">Number of posts: <%= @user.post_counter %> </p>
</div>

<% @user.posts.includes(:comments).each do |post| %>
  <div class="posts-container">
    <h2 id="post_<%= post.id %>"><%= link_to post.title, user_post_path(@user, post) %></h2>
    <p><%= post.text %></p>

    <div class="likes-div">
      <p>Comments: <%= post.comments.size %></p>
      <p class="likes">Likes: <%= post.likes.size %></p>
    </div>

    <ul class="comments-list">
      <% post.recent_comments.each do |comment| %>
        <li>
        <%= comment.user.name %>: <%= comment.text %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="pagination">
    <%= will_paginate @posts %>
</div>

app/views/posts/show.html.erb
<head>
  <%= stylesheet_link_tag 'application', 'posts_show' %>
</head>

<div class="header-div">
  <h1><%= @post.title %> by <%= @post.user.name %></h1>
  <div class="likes-div">
    <p>Likes: <%= @post.likes_counter %></p> 
    <p class="comments">Comments: <%= @post.comments_counter %></p>
  </div>
</div>

<div class="post-div">
  <p><%= @post.text %></p>
</div>

<div>
  <ul class="comments-list">
    <% @post.comments.includes(:user).each do |comment| %>
      <li>
        <%= comment.user.name %>: <%= comment.text %>
      </li>
    <% end %>
  </ul>
</div>

<h3>Create a Comment</h3>

<%= form_with(model: [@post, Comment.new], local: true, url: user_post_comments_path(current_user, @post)) do |form| %>
  <div class="field">
    <%= form.text_area :text, placeholder: 'Enter your comment here' %>
  </div>
  <div class="actions">
    <%= form.submit 'Create Comment' %>
  </div>
<% end %>
<%= form_with(model: [current_user, @post.likes.build], local: true, url: user_post_likes_path(current_user, @post)) do |form| %>
  <div class="actions">
    <%= form.hidden_field :user_id, value: current_user.id %>
    <%= form.submit 'Like', class: 'like-button' %>
  </div>
<% end %>

app/views/users/index.html.erb
<head>
  <%= stylesheet_link_tag 'application', 'users_index' %>
</head>

<ul class="users-list">
  <% @users.includes(:posts).each do |user| %>
    <li id="user_<%= user.id %>" class="user">
      <img src="<%= asset_path(user.photo) %>" alt="<%= user.name %>'s Photo" width="100" height="100" />
      <%= link_to user.name, user_path(user), class: 'user-name' %>
      <p class="no-posts">Number of Posts: <%= user.posts.size %></p>
    </li>
  <% end %>
</ul>

<%= form_with(model: [current_user, Post.new], local: true) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, placeholder: "Title" %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text, placeholder: "Text" %>
  </div>

  <div class="actions">
    <%= form.submit "Create Post" %>
  </div>
<% end %>

app/views/users/show.html.erb
<head>
  <%= stylesheet_link_tag 'application', 'users_show' %>
</head>

<div class="user-info">
  <img class="user-photo" src="<%= asset_path(@user.photo) %>" alt="<%= @user.name %>'s Photo" width="100" height="100" />
  <%= tag.div @user.name, class: 'user-name' %>
  <p class="no-posts">Number of posts: <%= @user.post_counter %> </p>
</div>

<div class="bio-container">
  <p>Bio</p>
  <%= @user.bio %>
</div>

<div class="posts-container">
  <ul class="posts-list">
    <% @user.recent_posts.includes(:comments, :likes).each do |post| %>
      <li class="list-item">
        <h2 id="post_<%= post.id %>"><%= link_to post.title, user_post_path(@user, post) %></h2>
        <p><%= post.text %></p>

        <div class="likes-div">
          <p>Comments: <%= post.comments.size %></p>
          <p class="likes">Likes: <%= post.likes.size %></p>
        </div>
      </li>
    <% end %>
  </ul>
</div>

<div class="btn-div">
  <%= link_to "See all Posts", user_posts_path(@user), class: "see-all-btn" %>
</div>